namespace Aynesil.Domain.Common;

/// <summary>
/// Root base class for all domain entities.
/// Uses UUID v7 (time-ordered) as the primary key — generated by the application
/// layer with Guid.CreateVersion7() or by the DB with core.uuid_generate_v7().
/// </summary>
public abstract class BaseEntity : IHasDomainEvents
{
    public Guid Id { get; protected set; } = Guid.CreateVersion7();

    private readonly List<IDomainEvent> _domainEvents = [];

    public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

    public void AddDomainEvent(IDomainEvent domainEvent) => _domainEvents.Add(domainEvent);

    public void RemoveDomainEvent(IDomainEvent domainEvent) => _domainEvents.Remove(domainEvent);

    public void ClearDomainEvents() => _domainEvents.Clear();

    public override bool Equals(object? obj)
    {
        if (obj is not BaseEntity other) return false;
        if (ReferenceEquals(this, other)) return true;
        if (GetType() != other.GetType()) return false;
        return Id == other.Id;
    }

    public override int GetHashCode() => Id.GetHashCode();

    public static bool operator ==(BaseEntity? left, BaseEntity? right) =>
        left?.Equals(right) ?? right is null;

    public static bool operator !=(BaseEntity? left, BaseEntity? right) =>
        !(left == right);
}
